/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: a1i_9 (https://sketchfab.com/a1i_9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-conditioning-system-d1367b53a8f541b39f6fbd8ce7bd4b48
Title: air conditioning system
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const AirConditioner = (props: any) => {
  const { scene, animations } = useGLTF("/air_conditioning_system.glb");
  const { actions } = useAnimations(animations, scene);
  useEffect(() => {
    if (actions) {
      actions["Cylinder.003Action"]?.play();
    }
  }, [actions]);

  return (
    <mesh>
      <primitive object={scene} />
    </mesh>
  );
};

export default AirConditioner;
