/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: a1i_9 (https://sketchfab.com/a1i_9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-conditioning-system-d1367b53a8f541b39f6fbd8ce7bd4b48
Title: air conditioning system
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const AirConditioner = (props) => {
  const group = useRef();
  const { nodes, materials, scene, animations } = useGLTF(
    "/air_conditioning_system.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      const firstAction = actions[Object.keys(actions)[0]];
      if (firstAction) {
        firstAction.play();
      }
    }
  }, [actions]);

  return (
    //   <mesh>
    //     <primitive object={scene} />
    //   </mesh>

    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" scale={[1, 1, 1.08]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.body}
                />
              </group>
              <group name="Plane001_2">
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane002_3" position={[0, -0.003, 0]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.body}
                />
              </group>
              <group name="Plane003_4">
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.body}
                />
              </group>
              <group name="Plane004_5" position={[-0.4, 1, 0.662]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="Cylinder001_6"
                position={[-0.4, 1, 0.662]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1, 1.021, 1]}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="NurbsPath_7"
                position={[-0.4, 1, 0.662]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.444, 1, 1]}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="NurbsPath001_8"
                position={[-0.4, 1, 0.662]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.44, 0.4, 0.4]}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="NurbsPath003_9"
                position={[-0.4, 1, 0.662]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.44, 1, 1]}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.cover}
                />
              </group>
              <group name="Circle_11" position={[0.852, 1.72, -0.707]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.market}
                />
              </group>
              <group name="Cylinder003_16" position={[-0.4, 1, 0.662]}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.material}
                />
                <group name="Plane006_12" position={[0, 0, -0.28]}>
                  <mesh
                    name="Object_26"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plane007_13"
                  position={[0, 0, -0.28]}
                  rotation={[0, 0, -1.484]}
                >
                  <mesh
                    name="Object_28"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plane008_14"
                  position={[0, 0, -0.28]}
                  rotation={[0, 0, -Math.PI]}
                >
                  <mesh
                    name="Object_30"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plane009_15"
                  position={[0, 0, -0.28]}
                  rotation={[0, 0, 1.658]}
                >
                  <mesh
                    name="Object_32"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.material}
                  />
                </group>
              </group>
              <group name="Cube001_17" position={[-0.108, 0.013, 0.648]}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="Bolt_18"
                position={[0.687, -0.016, 0.624]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.002}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Bolt001_19"
                position={[1.191, 1.956, 0.624]}
                scale={0.002}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Bolt002_20"
                position={[1.374, 1.97, 0.437]}
                scale={0.002}
              >
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Cylinder005_21"
                position={[-0.084, 1.895, -0.638]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1.599, 1.021, 1.599]}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.cover}
                />
              </group>
              <group
                name="Text001_22"
                position={[0.852, 1.72, 0.644]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.market}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

// useGLTF.preload("/air_conditioning_system.glb");
export default AirConditioner;
