/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mumladze28 (https://sketchfab.com/Mumladze28)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ceiling-fan-f5941cd91d094877b956ba58975d5bfe
Title: Stylized Ceiling fan
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

interface applianceStatusProps {
  status: boolean;
}

const CeilingFan = ({ status }: applianceStatusProps) => {
  const { animations, scene } = useGLTF("/stylized_ceiling_fan.glb");
  const { actions } = useAnimations(animations, scene);

  useEffect(() => {
    if (status) {
      if (actions) {
        actions["Fans|Fans Rot"]?.play();
      }
    } else {
      actions["Fans|Fans Rot"]?.stop();
    }
  }, [status, actions]);
  return (
    <mesh>
      <primitive object={scene} scale={0.5} />
    </mesh>
  );
};

useGLTF.preload("/stylized_ceiling_fan.glb");
export default CeilingFan;
