/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mumladze28 (https://sketchfab.com/Mumladze28)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ceiling-fan-f5941cd91d094877b956ba58975d5bfe
Title: Stylized Ceiling fan
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Mesh } from "three/src/Three.js";

const CeilingFan = (props: any) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/stylized_ceiling_fan.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      const firstAction = actions[Object.keys(actions)[0]];
      if (firstAction) {
        firstAction.play();
      }
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="6174e57527724a1a82ffc9d0deab4a80fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.25}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Ceiling_fan"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Ceiling_fan_CeilingfanMat_0"
                    castShadow
                    receiveShadow
                    geometry={
                      (nodes.Ceiling_fan_CeilingfanMat_0 as Mesh).geometry
                    }
                    material={materials.CeilingfanMat}
                  />
                  <mesh
                    name="Ceiling_fan_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={(nodes.Ceiling_fan_Outline_0 as Mesh).geometry}
                    material={materials.Outline}
                  />
                  <group name="Fans">
                    <mesh
                      name="Fans_CeilingfanMat_0"
                      castShadow
                      receiveShadow
                      geometry={(nodes.Fans_CeilingfanMat_0 as Mesh).geometry}
                      material={materials.CeilingfanMat}
                    />
                    <mesh
                      name="Fans_Outline_0"
                      castShadow
                      receiveShadow
                      geometry={(nodes.Fans_Outline_0 as Mesh).geometry}
                      material={materials.Outline}
                    />
                  </group>
                </group>
                <group
                  name="Ceiling"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Ceiling_CeilingMat_0"
                    castShadow
                    receiveShadow
                    geometry={(nodes.Ceiling_CeilingMat_0 as Mesh).geometry}
                    material={materials.CeilingMat}
                  />
                  <mesh
                    name="Ceiling_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={(nodes.Ceiling_Outline_0 as Mesh).geometry}
                    material={materials.Outline}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/stylized_ceiling_fan.glb");
export default CeilingFan;
