/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: goakley (https://sketchfab.com/goakley)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-ceiling-light-fixture-edafa17f987a43f5adbff33652fe7a9c
Title: Modern Ceiling Light Fixture
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";
import * as THREE from "three";

const CeilingLight = ({ status }) => {
  const { nodes, materials } = useGLTF("/modern_ceiling_light_fixture.glb");
  const bulbRef = useRef(null);
  const bulbMaterial = materials.Bulb;

  const { rotation } = useSpring({
    from: { rotation: [0, 0, 0] },
    to: { rotation: status ? [0, Math.PI / 2, 0] : [0, 0, 0] },
    config: { duration: 5000 },
    loop: true,
  });

  useEffect(() => {
    if (bulbMaterial) {
      if (status) {
        bulbMaterial.emissive = new THREE.Color(1, 1, 0); // Yellow light
        bulbMaterial.emissiveIntensity = 1;
      } else {
        bulbMaterial.emissiveIntensity = 0;
      }
    }
  }, [status, bulbMaterial]);

  return (
    <a.group ref={bulbRef} rotation={rotation} dispose={null}>
      <group scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Bronze}
        />
        <mesh
          ref={bulbRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={bulbMaterial}
        />
      </group>
      <group rotation={[0, Math.PI / 3, 0]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.Bulb}
        />
      </group>
      <group rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.Bulb}
        />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Bulb}
        />
      </group>
      <group rotation={[Math.PI, -Math.PI / 3, Math.PI]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.Bulb}
        />
      </group>
      <group rotation={[0, -Math.PI / 3, 0]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.Bulb}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Bronze}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Bronze}
        position={[0, 0.465, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Bronze}
        position={[0, 0.152, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Bronze}
        position={[0, 0.272, 0]}
      />
    </a.group>
  );
};

useGLTF.preload("/modern_ceiling_light_fixture.glb");
export default CeilingLight;
