/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: allenbranch (https://sketchfab.com/allenbranch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ge-profile-double-oven-electric-range-e2ee65bf1c8b40ac8b78fe6a1e392575
Title: GE Profile Double Oven Electric Range
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";

interface applianceStatusProps {
  status: boolean;
}

const ElectricOven = ({ status }: applianceStatusProps) => {
  const { scene } = useGLTF("/ge_profile_double_oven_electric_range.glb");

  const { rotation } = useSpring({
    from: { rotation: [0, 0, 0] },
    to: { rotation: status ? [0, Math.PI / 4, 0] : [0, 0, 0] },
    config: { duration: 5000 },
    loop: true,
  });

  return (
    <>
      <a.mesh
        // must specify each axis separately to avoid typescript error
        // underscore placeholders ignore unused values
        rotation-x={rotation.to((x) => x)}
        rotation-y={rotation.to((_, y) => y)}
        rotation-z={rotation.to((_, __, z) => z)}
      >
        <primitive object={scene} />
      </a.mesh>
    </>
  );
};

export default ElectricOven;
