/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: allenbranch (https://sketchfab.com/allenbranch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ge-profile-double-oven-electric-range-e2ee65bf1c8b40ac8b78fe6a1e392575
Title: GE Profile Double Oven Electric Range
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const ElectricOven = (props: any) => {
  const { scene } = useGLTF("/ge_profile_double_oven_electric_range.glb");
  return (
    <>
      <mesh>
        <primitive object={scene} />
      </mesh>
    </>
  );
};

export default ElectricOven;
