/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: moanatari (https://sketchfab.com/moanatari)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/litle-floating-island-in-low-poly-96bf4ef7cd6b40cf98fbc07d17e4abd4
Title: Litle floating island in low poly
*/

"use client";

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Island = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/litle_floating_island_in_low_poly.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      const firstAction = actions[Object.keys(actions)[0]];
      if (firstAction) {
        firstAction.play();
      }
    }
  }, [actions]);

  useEffect(() => {
    const rotateIsland = () => {
      if (group.current) {
        group.current.rotation.y += 0.001;
      }
      requestAnimationFrame(rotateIsland);
    };
    rotateIsland();

    return () => {
      cancelAnimationFrame(rotateIsland);
    };
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[-0.408, 0, 0.673]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.028}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane001_0" position={[-0.461, 0, 0]} scale={8.295}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Water_Material}
                />
              </group>
              <group
                name="Plane003_1"
                position={[-2.881, 1.609, -6.945]}
                rotation={[0.083, -0.03, 0.138]}
                scale={0.179}
              >
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Plane004_2"
                position={[-3.436, 1.402, -6.611]}
                rotation={[0.037, -0.007, 0.077]}
                scale={0.165}
              >
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Plane005_3"
                position={[-4.416, 0.958, -6.056]}
                rotation={[-0.05, 0.046, -0.039]}
                scale={0.199}
              >
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Plane006_4"
                position={[-2.954, 0.74, -4.519]}
                rotation={[0.016, 0.032, -0.12]}
                scale={0.181}
              >
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Plane007_5"
                position={[-7.019, 1.161, 2.91]}
                rotation={[-0.018, 0.06, 0.048]}
                scale={0.106}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="Plane008_6"
                position={[6.741, 1.416, -2.277]}
                rotation={[0.137, 0.09, -0.041]}
                scale={0.131}
              >
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.006"]}
                />
              </group>
              <group
                name="BigTree_8"
                position={[-1.677, -0.179, -13.035]}
                rotation={[Math.PI, -1.112, Math.PI]}
                scale={0.146}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.TreeBrownPlus}
                />
                <group
                  name="BigTreeLeafs_7"
                  position={[11.837, 16.753, 1.752]}
                  scale={6.837}
                >
                  <mesh
                    name="Object_26"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.TreeGreen}
                  />
                </group>
              </group>
              <group
                name="Tree001_11"
                position={[8.017, 1.063, 4.262]}
                rotation={[-Math.PI, -0.455, -Math.PI]}
                scale={0.14}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.TreeBrown}
                />
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.TreeBrownPlus}
                />
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.TreeGreen}
                />
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="Icosphere001_12"
                position={[0.382, 1.882, 1.249]}
                scale={0.309}
              >
                <mesh
                  name="Object_33"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_33.geometry}
                  material={materials.TreeGreen}
                />
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="Icosphere002_13"
                position={[1.568, -0.757, -12.179]}
                rotation={[0, 0.408, 0]}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.IsleGround}
                />
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.IsleGreen}
                />
              </group>
              <group
                name="Icosphere003_14"
                position={[5.84, -6.843, -5.808]}
                rotation={[-0.57, -0.314, -0.153]}
              >
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.IsleGround}
                />
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.IsleGreen}
                />
              </group>
              <group
                name="Icosphere004_15"
                position={[-1.107, -8.299, -6.856]}
                rotation={[0.104, -0.028, 0.393]}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.IsleGround}
                />
              </group>
              <group
                name="Rock_16"
                position={[6.244, 2.286, 5.913]}
                rotation={[0.191, 0.701, 1.385]}
                scale={[0.661, 1.692, 1.013]}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock001_17"
                position={[-0.496, 1.238, 6.849]}
                rotation={[-0.726, -0.185, -1.653]}
                scale={[0.661, 0.648, 0.778]}
              >
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock002_18"
                position={[8.043, -1.566, 4.396]}
                rotation={[-1.579, -0.154, -0.134]}
                scale={[1.826, 2.348, 1.826]}
              >
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock003_19"
                position={[2.338, -5.177, -7.975]}
                rotation={[-1.089, 0.065, -0.039]}
                scale={[3.973, 3.192, 3.629]}
              >
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock004_20"
                position={[-5.456, 3.06, -2.726]}
                rotation={[-1.839, -0.188, -0.319]}
                scale={[2.478, 1.991, 2.263]}
              >
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock005_21"
                position={[5.769, 1.566, 6.338]}
                rotation={[0.049, 0.883, 0.089]}
                scale={[0.658, 1.241, 0.999]}
              >
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Rock006_22"
                position={[6.565, 1.381, 5.744]}
                rotation={[0.058, -0.998, 0.176]}
                scale={[0.661, 1.52, 0.999]}
              >
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="Tree002_23"
                position={[-2.099, 0.748, 6.783]}
                rotation={[0.268, -0.973, 0.241]}
                scale={0.099}
              >
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.TreeBrown}
                />
                <mesh
                  name="Object_59"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={materials.TreeBrownPlus}
                />
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.TreeGreen}
                />
                <mesh
                  name="Object_61"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="Tree003_24"
                position={[1.888, 0.415, 1.841]}
                rotation={[2.8, 0.867, -2.794]}
                scale={0.115}
              >
                <mesh
                  name="Object_63"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={materials.TreeBrown}
                />
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.TreeBrownPlus}
                />
                <mesh
                  name="Object_65"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={materials.TreeGreen}
                />
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="Tree004_25"
                position={[8.072, -1.182, -4.815]}
                rotation={[-2.646, -0.997, -1.917]}
                scale={0.14}
              >
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.TreeBrown}
                />
                <mesh
                  name="Object_69"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials.TreeBrownPlus}
                />
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.TreeGreen}
                />
                <mesh
                  name="Object_71"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_71.geometry}
                  material={materials["Material.004"]}
                />
              </group>
              <group
                name="Clouds_26"
                position={[-1.936, 8.104, -1.123]}
                scale={0.781}
              >
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials["Material.007"]}
                />
              </group>
              <group name="Icosphere_27" scale={10}>
                <mesh
                  name="Object_75"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials.IcoSphere_Material}
                />
              </group>
              <group
                name="RockTree_28"
                position={[2.008, 1.428, -12.602]}
                rotation={[0.099, 1.152, -0.244]}
                scale={[0.597, 0.476, 0.5]}
              >
                <mesh
                  name="Object_77"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_77.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name="RockTree001_29"
                position={[4.718, -5.735, -7.473]}
                rotation={[-0.009, 1.129, -0.225]}
                scale={[0.364, 0.291, 0.305]}
              >
                <mesh
                  name="Object_79"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials.Rock}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/litle_floating_island_in_low_poly.glb");
export default Island;
