/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ramos301 (https://sketchfab.com/ramos301)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-fixture-2da4cca1c6054952a4cfffa6011ab0f9
Title: light fixture
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const PorchLight = (props) => {
  const { scene } = useGLTF("/light_fixture.glb");
  return (
    <mesh>
      <primitive object={scene} />
    </mesh>
  );
};

useGLTF.preload("/light_fixture.glb");
export default PorchLight;
