/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nommoc (https://sketchfab.com/kikumi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/refrigerator-9eeff266683a464a9a3cc1e6a2f8af28
Title: Refrigerator
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Refrigerator = (props: any) => {
  const { scene, animations } = useGLTF("/refrigerator.glb");
  const { actions } = useAnimations(animations, scene);

  useEffect(() => {
    if (actions) {
      actions["Animation"]?.play();
    }
  }, [actions]);
  return (
    <mesh>
      <primitive object={scene} />
    </mesh>
  );
};

export default Refrigerator;
