/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Mesh } from "three/src/Three.js";
import * as THREE from "three";

const Sky = () => {
  const { nodes, materials } = useGLTF("/sky.glb");
  const ref = useRef<THREE.Group>(null!);

  useFrame(() => {
    ref.current.rotation.y += 0.0005;
  });
  return (
    <group dispose={null} ref={ref}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Sphere__0 as Mesh).geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={30000}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/sky.glb");
export default Sky;
