/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: James Rogers (https://sketchfab.com/JamesRogers)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-glass-table-sketchfab-40ca38263bcd413381294aa791296719
Title: TV & Glass Table Sketchfab
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Television = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/tv__glass_table_sketchfab.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Glass_Table_Top_0"
                position={[0.296, -0.423, -0.004]}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Glass_Table}
                />
              </group>
              <group name="Stand_1" position={[-0.554, -0.632, 0.163]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Stands}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Stands}
                />
              </group>
              <group
                name="Glass_Table_Bottom_2"
                position={[0.296, -0.587, -0.004]}
              >
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Glass_Table}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.Glass_Table}
                />
              </group>
              <group name="TV_3" position={[0.296, -0.625, -0.004]}>
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.TV_Receiver}
                />
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.material}
                />
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.TV_Screen}
                />
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.TV_Logo}
                />
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.TV_Ports}
                />
              </group>
              <group name="Stand_Base_4" position={[0.296, -0.609, -0.004]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Stands_5" position={[0.296, -0.609, -0.004]}>
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.material}
                />
              </group>
              <group
                name="Stand_Knots_6"
                position={[0.296, -0.587, -0.004]}
                scale={[1, 1, 1.029]}
              >
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.Stand_Knots}
                />
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Stand_Knots}
                />
              </group>
              <group
                name="Button_Power_7"
                position={[1.221, 0.943, -0.004]}
                scale={[0.004, 0.002, 0.004]}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Power_Button}
                />
              </group>
              <group
                name="Button_Volume_-_8"
                position={[1.192, 0.943, -0.004]}
                scale={[0.004, 0.002, 0.004]}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Volume_-_Button"]}
                />
              </group>
              <group
                name="Button_Volume_+_9"
                position={[1.205, 0.943, -0.004]}
                scale={[0.004, 0.002, 0.004]}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.Volume__Button}
                />
              </group>
              <group
                name="HDMI_10"
                position={[-0.412, 0.124, -0.01]}
                rotation={[-Math.PI, 0, -Math.PI]}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.HDMI}
                />
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.HDMI}
                />
              </group>
              <group
                name="HDMI_2_11"
                position={[-0.412, 0.124, -0.01]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.006, 0, 0.002]}
              >
                <mesh
                  name="Object_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials.HDMI_2}
                />
              </group>
              <group
                name="USB_12"
                position={[-0.432, 0.124, -0.01]}
                rotation={[Math.PI, 0, Math.PI]}
              >
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.HDMI}
                />
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.HDMI}
                />
              </group>
              <group name="USB_2_13" position={[-0.432, 0.125, -0.011]}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.HDMI_2}
                />
              </group>
              <group name="Audio_Yellow_14" position={[-0.45, 0.123, -0.012]}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials["3_Ports"]}
                />
              </group>
              <group name="Audio_Yellow_2_15" position={[-0.45, 0.123, -0.012]}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials["3_Ports_Yellow"]}
                />
              </group>
              <group name="Audio_White_16" position={[-0.45, 0.11, -0.012]}>
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials["3_Ports"]}
                />
              </group>
              <group name="Audio_White_2_17" position={[-0.45, 0.11, -0.012]}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials["3_Ports_White"]}
                />
              </group>
              <group name="Audio_Red_18" position={[-0.45, 0.098, -0.012]}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials["3_Ports"]}
                />
              </group>
              <group name="Audio_Red_2_19" position={[-0.45, 0.098, -0.012]}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials["3_Ports_Red"]}
                />
              </group>
              <group
                name="Headphone_Jack_20"
                position={[-0.45, 0.084, -0.011]}
                scale={0.709}
              >
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.Headphones}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/tv__glass_table_sketchfab.glb");
export default Television;
