/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: James Rogers (https://sketchfab.com/JamesRogers)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-glass-table-sketchfab-40ca38263bcd413381294aa791296719
Title: TV & Glass Table Sketchfab
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";

interface applianceStatusProps {
  status: boolean;
}

const Television = ({ status }: applianceStatusProps) => {
  const { scene } = useGLTF("/tv__glass_table_sketchfab.glb");

  const { rotation } = useSpring({
    from: { rotation: [0, 0, 0] },
    to: { rotation: status ? [0, Math.PI / 4, 0] : [0, 0, 0] },
    config: { duration: 5000 },
    loop: true,
  });

  return (
    <a.mesh // must specify each axis separately to avoid typescript error
      // underscore placeholders ignore unused values
      rotation-x={rotation.to((x) => x)}
      rotation-y={rotation.to((_, y) => y)}
      rotation-z={rotation.to((_, __, z) => z)}
    >
      <primitive object={scene} />
    </a.mesh>
  );
};

export default Television;
