/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: James Rogers (https://sketchfab.com/JamesRogers)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-glass-table-sketchfab-40ca38263bcd413381294aa791296719
Title: TV & Glass Table Sketchfab
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Television = (props) => {
  const { scene } = useGLTF("/tv__glass_table_sketchfab.glb");

  return (
    <mesh>
      <primitive object={scene} />
    </mesh>
  );
};

useGLTF.preload("/tv__glass_table_sketchfab.glb");
export default Television;
