/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CloudHub (https://sketchfab.com/cloudhub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mielewasheranddryer-5688602a90504ea2aff1691772e4db8c
Title: Miele+washer+and+dryer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const WasherDryer = (props) => {
  const { scene } = useGLTF("/mielewasheranddryer.glb");
  return (
    <mesh>
      <primitive object={scene} />
    </mesh>
  );
};

useGLTF.preload("/mielewasheranddryer.glb");
export default WasherDryer;
